// <auto-generated />
namespace lee_hankins_backend_capstone.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class firstLineItemDb1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(firstLineItemDb1));
        
        string IMigrationMetadata.Id
        {
            get { return "201706100137107_firstLineItemDb1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
